name: Release

on: 
  push:
    tags:
      - "v*"
  
jobs:
  docker-docgen:
    name: Release DocGen Image and API Doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          skip-save: true
          key: foo-docker-cache-{hash}
          restore-keys: |
            foo-docker-cache-
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        run: |
          docker build -f Dockerfile.docgen -t s41m0n/dechainy:docgen .
          docker image push s41m0n/dechainy:docgen

  docker-test:
    name: Release Test Image
    runs-on: ubuntu-latest
    needs: docker-docgen
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          skip-save: true
          key: foo-docker-cache-{hash}
          restore-keys: |
            foo-docker-cache-
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        run: |
          docker build --build-arg DEFAULT_BUILDTYPE=test -f Dockerfile -t s41m0n/dechainy:test .
          docker image push s41m0n/dechainy:test

  docker-latest:
    name: Release Latest Image
    runs-on: ubuntu-latest
    needs: docker-docgen
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          skip-save: true
          key: foo-docker-cache-{hash}
          restore-keys: |
            foo-docker-cache-
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        run: |
          docker build --build-arg DEFAULT_BUILDTYPE=default -f Dockerfile -t s41m0n/dechainy:latest .
          docker image push s41m0n/dechainy:latest

  docker-ml-cpu:
    name: Release ML-CPU image
    runs-on: ubuntu-latest
    needs: docker-docgen
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          skip-save: true
          key: foo-docker-cache-{hash}
          restore-keys: |
            foo-docker-cache-
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        run: |
          docker build --build-arg DEFAULT_BUILDTYPE=ml -f Dockerfile -t s41m0n/dechainy:ml-cpu .
          docker image push s41m0n/dechainy:ml-cpu

  docker-ml-gpu:
    name: Release ML-GPU image
    runs-on: ubuntu-latest
    needs: docker-docgen
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          skip-save: true
          key: foo-docker-cache-{hash}
          restore-keys: |
            foo-docker-cache-
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        run: |
          docker build -f Dockerfile.gpu -t s41m0n/dechainy:ml-gpu .
          docker image push s41m0n/dechainy:ml-gpu
      
